version: '3.8'

services:
  redis:
    # Use the redis:alpine image from Docker Hub
    image: redis:alpine
    container_name: db-redis
    ports:
    - "6379:6379"
    volumes:
    - redis_data:/data
    networks:
      - internal-network

    # up at docker startup
    restart: unless-stopped

volumes:
  redis_data:

networks:
  internal-network:
    external: true
